sudo: required
addons:
  apt:
    update: true
    packages:
    - docker-ce
services:
- docker
before_script: 
script:
- timetag=$(date +%Y%m%d%H%M)
- "./docker-build.sh vmnet8/nginx-tags:$timetag"
- echo "$DOCKERPASSWD" | docker login -u "$DOCKERUSERNAME" --password-stdin
- docker push vmnet8/nginx-tags:$timetag
before_deploy:
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
  - secure: rtGdM633rP1ehqUx97+gJ4Hk2kZFVkejsf+YMD+r3dEpDhcOl7F5UkA8s2GiPKLTQy4PYzbOB7SnyzG3kmE/EH2fpRZkZ+0UXeK6aKCHiQQc41gtuHDVNLH9+ub8xFSYfww4c25GBdMUoOy1MFycLXAo/PyVhoJBVXG/iXru4KRbj6p1O9ZsH7dyW+oeLgaHRPwCVS1mn7kkxLZI/CBA6kn2zQS1ve5oLAMwi3T5X7/FThkrHXhskaL+86D1KxD5YQAtRSCJvWwbJ8MZtSy8c+MKcsiBwVLsQiQJM5waBv7YYlBrpiC605Bb9cutfVEXWSbwVfBuwKavHURXjcgJlOGNVMnSN/KESN0X+SJO7R+MkCcEgLvKetfpSp/MxU7Ol3e2qw+OsyfD6Dm78VfxySEdfR3O0Zn6PWddFJkNU7TpQhcq6NRYnkozpp/86af0WB9mLo1D0RzmAWgfHWqF9wttUrbVNAL0lOaMRLVE1q3SOuRnpwPB8jncrbvcEIRi6jhS+p0HwKw7pqxpQyls1wu+FeP0RXGY2xwRd6ouCsHZwcRy6tydNKUHoRe4nk3ir3Jrsdu4D5KVkZ2geRGCBiDcvTbO511dlw9E8vYwdBRuQskf5d2ngHQNCM5Xnbn1k2SwuEoKRRlLe1FAkxOQlyZ+z1bQnmJaLuIsS40jUnY=
  - secure: w1ERWN4GdFDBGicJyZDhJA9ekH1EeEKQz4i5Snlvrfr6LYJTL7oCJ9kB2eikkNtQ+KTaz0MlJ7bKjUoW0zM+eDE5V8nhCE/COYFTGWKrg0mfOTCgP6PL/Nnthqx0AZeYpIXwzPcwF/NTplTy8IddmwUob90Y7Vvl7VF84R9vPSMCB3jYm/pXgoD41JVSulmOgfW/D0f7sPsk6Qc/vIrD79BMB1TcL11PCYF/0Vjy/ymCjqM+UF32PE8i2icDkwvTIeu1fMgDWM6sym6QHCJywr8LbU4Q+J7b/G6I1EqnpQ/U7Xde6NCPKdi/v3LLDighQUIx3riX/f1CnCg0aDkp1/pF5RDpYt7WY8buUDxtQ0RoMCFAquksTVwIBKpTnxYl/7Z/Nysqzu/4kSC7BEt8fejpP7oDQEPWSVByzrmUPCLRU3BfvHh1aMoEX8nOLllrjgWVEMuHO0z/ZlyoEM8MlG75qv6upnVDY5b2CGftzJbk1v7H2Y+JdJkzvxMZGK3zH7bX7431c68qHvMoJvrU3u62sqv5N3urPk1z8V4kZVjXB7b2C47NoR/jPVSVrLY7Jr3+YpWAzoEa5ETa4GfQRl4SGiFS5uLrknUxxhtkRp0MicjZ2P6/1O/rP4TLRTO3TMYHfJHwCzlVCS2mzJ3snfbid+t5NfQsAYm5RVIa9YI=
  - secure: qqHhT81x6KPuQ2O7TbwKWgj9ROl65AEjhVX9Hl8/5pnpcVkzqLBQi2DuVxVJ27iGeWRZG+h6wMym77hJ49qY47nz17AvcyizUfIVo50uRWOnM66hdWX+6pbujhb5iIzjCIg29ylJJ7862RLIGUoFQl2fOIQUMh8OKktEzTJMU90ozf6hl8+Kdc6zFxCqgzss9hWmgvw3TZOyW04bPMDZ91oadQpu2GK8BCTGB8w+2eGyGx3XhrIhej1CVtTPJSBUMBTEgW4v2WVCjjvPqDm/0zsdJ/m9vPdC2JwGA0xkdO20fRwB/A9RwEHx8YL5/nyrghsZg0OSCuLGC2E3+e5mAZD0kkQmdMeMrGLvZ+TU+wmMGUpzd48YPn29lT2tAAeSZkDXNSbjSD594ip1rSAmrmUN5cN1axeQl/SRJBLl6JAxZqicovkB8qZ4O0ay0FhK996eW+yKxnVWkVXC/ntBTEldd9C5zDBpH0pNqWmrhVAZTlNawjBypPNc3XPlcwm+HtT6J4EUG+vVN7BiGDihmBF34WlQbVp0uABpJe8qXikB0sdgHVDTA8nI5COohBGfCa2fYRmbqZTGm9N3ZMo7o/ZwlPz/qVED6JD5ATZizsIZevXVg/lfnhZJBw0onswC6LDU+uZ1kPBQ2sSsm5Tui5CHUDlRrpXd3g7Td5ZI8TM=
