sudo: required
addons:
  apt:
    update: true
    packages:
    - docker-ce
services:
- docker
before_script:

script:
- ./docker-build.sh
#- export DOCKER_CLI_EXPERIMENTAL=enabled
#- docker build -t vmnet8/nginx-tags:test  -f Dockerfile
#- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
before_deploy:
#deploy:
#- provider: script
 # script: docker manifest push vmnet8/alpine:$tag; docker manifest push vmnet8/alpine:$tag2
  skip_cleanup: true
  on:
    all_branches: true
#    condition: $flag
env:
  global:
  - secure: R+mSAK87xrYZCtiPbtu2WyiKV900lTnIErn2QtQz2DDz6ed0+dROeQ+yjANiaRgUsclAEsK2cq6E+3IkjOTukZchmth1H4J5MIkRu5a6zb8ZwxBPvjJgcLHYMBiMLp6u8FyyKNPYM86Qc7H/jCc4F0bb/unZGikiHwzdyEMd0wxXs5g/DnUtQanqKKw20yhM8HpzdyYNhR1fx7jwvCuRspmRovTjSqP/zm0S9/RzAl9BpjaI4s9MLX2fSMzELtnZ0nGo1AL6Qc0lFKhaMNdAQ/mhyjgj083cq7PAp4xYZg4QClXoCOAEgaKzb9mkiAE741+5LV79a1dHyxo3z5/Qry/ZlUrOIJ8IIZ8nU3h6zA9A0nJbYW2u1/2dLlf2pIphM+TUE3MTuE5hvEZd4mTLl7Cf9NDKVA3aI4v6zGD57AjM+Zi3+lGU85cOGBQO8kYjR1VRfVQX1OKQKbpCKj+h5d86xEdWlshY4cZb0MK1Xy1zJgTwqX6AEOQJ3N8J3c4DBYNTN4pP9rdaN7h/q+47kldsdYJlSK72IqedVPOloGpzBo3n67BlIkSYG47UMJgzDxgPjK/lzosMWLjBFGUxgkPXswPulFWEWR0+qK5663k/6Wv3/mke4X7hWtXMM9zH0xFvqxSr8fakMiRySml14pgbEKsz4vDF2C7XaALBJjc=

