sudo: required
addons:
  apt:
    update: true
    packages:
    - docker-ce
services:
- docker
before_script: 
script:
- timetag=$(date +%Y%m%d%H%M)
- ./docker-build.sh vmnet8/nginx-tags:$timetag
- echo "$DOCKERPASSWD" | docker login -u "$DOCKERUSERNAME" --password-stdin
- docker push vmnet8/nginx-tags:$timetag
before_deploy:
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
